CREATE TABLE IF NOT EXISTS "aspirante" (
	"id_aspirante" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_tipo_ingreso" INTEGER NOT NULL,
	"id_aspirante_opcion" VARCHAR(256),
	"nombres" VARCHAR(64) NOT NULL,
	"apellidos" VARCHAR(64) NOT NULL,
	"observaciones" TEXT,
	PRIMARY KEY("id_aspirante")
);




CREATE TABLE IF NOT EXISTS "examen" (
	"id_examen" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_tipo_examen" INTEGER NOT NULL,
	"observaciones" TEXT,
	PRIMARY KEY("id_examen")
);




CREATE TABLE IF NOT EXISTS "jornada" (
	"id_jornada" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_docente_encargado" VARCHAR(256),
	"id_aula" VARCHAR(256),
	"observaciones" TEXT,
	PRIMARY KEY("id_jornada")
);




CREATE TABLE IF NOT EXISTS "examen_jornada" (
	"id_examen_jornada" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_examen" INTEGER NOT NULL,
	"id_jornada" INTEGER NOT NULL,
	"inicio" TIMESTAMPTZ NOT NULL,
	"fin" TIMESTAMPTZ NOT NULL,
	"observaciones" TEXT,
	PRIMARY KEY("id_examen_jornada")
);




CREATE TABLE IF NOT EXISTS "examen_aspirante" (
	"id_examen_aspirante" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_aspirante" BIGINT NOT NULL,
	"id_examen" INTEGER NOT NULL,
	"ruta" VARCHAR(256),
	"calificacion" DOUBLE PRECISION,
	"observaciones" TEXT,
	PRIMARY KEY("id_examen_aspirante")
);




CREATE TABLE IF NOT EXISTS "tipo_ingreso" (
	"id_tipo_ingreso" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"nombre" VARCHAR(64) NOT NULL,
	"observaciones" TEXT,
	PRIMARY KEY("id_tipo_ingreso")
);




CREATE TABLE IF NOT EXISTS "tipo_examen" (
	"id_tipo_examen" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"nombre" VARCHAR(64) NOT NULL,
	"observaciones" TEXT,
	PRIMARY KEY("id_tipo_examen")
);




CREATE TABLE IF NOT EXISTS "documento_identificacion" (
	"id_documento_identificacion" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_aspirante" BIGINT NOT NULL,
	"id_tipo_documento_identificacion" INTEGER NOT NULL,
	"vigente" BOOLEAN NOT NULL DEFAULT FALSE,
	"numero" INTEGER NOT NULL UNIQUE,
	"observaciones" TEXT,
	PRIMARY KEY("id_documento_identificacion")
);




CREATE TABLE IF NOT EXISTS "tipo_documento_identificacion" (
	"id_tipo_documento_identificacion" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"nombre" VARCHAR(64) NOT NULL UNIQUE,
	"observaciones" TEXT,
	PRIMARY KEY("id_tipo_documento_identificacion")
);




CREATE TABLE IF NOT EXISTS "examen_area_conocimiento" (
	"id_examen_area_conocimiento" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_examen" INTEGER NOT NULL,
	"id_area_conocimiento" INTEGER NOT NULL,
	"observaciones" TEXT,
	PRIMARY KEY("id_examen_area_conocimiento")
);




CREATE TABLE IF NOT EXISTS "area_conocimiento" (
	"id_area_conocimiento" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_area_conocimiento_padre" INTEGER,
	"nombre" VARCHAR(128) NOT NULL,
	"observaciones" TEXT,
	PRIMARY KEY("id_area_conocimiento")
);




CREATE TABLE IF NOT EXISTS "pregunta" (
	"id_pregunta" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"enunciado" VARCHAR(256) NOT NULL,
	"respuesta" VARCHAR(64) NOT NULL,
	"observaciones" TEXT,
	PRIMARY KEY("id_pregunta")
);




CREATE TABLE IF NOT EXISTS "pregunta_area_conocimiento" (
	"id_pregunta_area_conocimiento" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_area_conocimiento" INTEGER NOT NULL,
	"id_pregunta" BIGINT NOT NULL,
	"observaciones" TEXT,
	PRIMARY KEY("id_pregunta_area_conocimiento")
);




CREATE TABLE IF NOT EXISTS "examen_area_conocimiento_pregunta" (
	"id_examen_area_conocimiento_pregunta" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_examen_area_conocimiento" BIGINT NOT NULL,
	"id_pregunta" BIGINT NOT NULL,
	"ponderacion" DOUBLE PRECISION NOT NULL,
	"observaciones" TEXT,
	PRIMARY KEY("id_examen_area_conocimiento_pregunta")
);




CREATE TABLE IF NOT EXISTS "distractor" (
	"id_distractor" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"valor" VARCHAR(64) NOT NULL,
	"observaciones" TEXT,
	PRIMARY KEY("id_distractor")
);




CREATE TABLE IF NOT EXISTS "pregunta_distractor" (
	"id_pregunta_distractor" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_pregunta" BIGINT NOT NULL,
	"id_distractor" BIGINT NOT NULL,
	"observaciones" TEXT,
	PRIMARY KEY("id_pregunta_distractor")
);




CREATE TABLE IF NOT EXISTS "distractor_area_conocimiento" (
	"id_distractor_area_conocimiento" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_area_conocimiento" INTEGER NOT NULL,
	"id_distractor" BIGINT NOT NULL,
	"observaciones" TEXT,
	PRIMARY KEY("id_distractor_area_conocimiento")
);



ALTER TABLE "examen_area_conocimiento"
ADD FOREIGN KEY("id_area_conocimiento") REFERENCES "area_conocimiento"("id_area_conocimiento")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "examen_area_conocimiento"
ADD FOREIGN KEY("id_examen") REFERENCES "examen"("id_examen")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "examen_jornada"
ADD FOREIGN KEY("id_jornada") REFERENCES "jornada"("id_jornada")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "examen_aspirante"
ADD FOREIGN KEY("id_aspirante") REFERENCES "aspirante"("id_aspirante")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "examen_aspirante"
ADD FOREIGN KEY("id_examen") REFERENCES "examen"("id_examen")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "examen_jornada"
ADD FOREIGN KEY("id_examen") REFERENCES "examen"("id_examen")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "examen"
ADD FOREIGN KEY("id_tipo_examen") REFERENCES "tipo_examen"("id_tipo_examen")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "aspirante"
ADD FOREIGN KEY("id_tipo_ingreso") REFERENCES "tipo_ingreso"("id_tipo_ingreso")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "documento_identificacion"
ADD FOREIGN KEY("id_aspirante") REFERENCES "aspirante"("id_aspirante")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "documento_identificacion"
ADD FOREIGN KEY("id_tipo_documento_identificacion") REFERENCES "tipo_documento_identificacion"("id_tipo_documento_identificacion")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "area_conocimiento"
ADD FOREIGN KEY("id_area_conocimiento_padre") REFERENCES "area_conocimiento"("id_area_conocimiento")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "pregunta_area_conocimiento"
ADD FOREIGN KEY("id_pregunta") REFERENCES "pregunta"("id_pregunta")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "pregunta_area_conocimiento"
ADD FOREIGN KEY("id_area_conocimiento") REFERENCES "area_conocimiento"("id_area_conocimiento")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "pregunta_distractor"
ADD FOREIGN KEY("id_distractor") REFERENCES "distractor"("id_distractor")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "pregunta_distractor"
ADD FOREIGN KEY("id_pregunta") REFERENCES "pregunta"("id_pregunta")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "distractor_area_conocimiento"
ADD FOREIGN KEY("id_area_conocimiento") REFERENCES "area_conocimiento"("id_area_conocimiento")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "distractor_area_conocimiento"
ADD FOREIGN KEY("id_distractor") REFERENCES "distractor"("id_distractor")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "examen_area_conocimiento_pregunta"
ADD FOREIGN KEY("id_examen_area_conocimiento") REFERENCES "examen_area_conocimiento"("id_examen_area_conocimiento")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "examen_area_conocimiento_pregunta"
ADD FOREIGN KEY("id_pregunta") REFERENCES "pregunta"("id_pregunta")
ON UPDATE NO ACTION ON DELETE NO ACTION;