BEGIN;

CREATE TABLE IF NOT EXISTS public.area_conocimiento
(
    id_area_conocimiento INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_area_conocimiento_padre INTEGER,
    nombre character varying(64) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    activo boolean,
    CONSTRAINT area_pkey PRIMARY KEY (id_area_conocimiento)
);

CREATE TABLE IF NOT EXISTS public.aspirante
(
    id_aspirante BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nombres character varying(64) NOT NULL,
    apellidos character varying(64) NOT NULL,
    fecha_nacimiento date NOT NULL,
    correo character varying(124) COLLATE pg_catalog."default" NOT NULL,
    fecha_creacion timestamp with time zone DEFAULT now(),
    observaciones text COLLATE pg_catalog."default",
    CONSTRAINT aspirante_pkey PRIMARY KEY (id_aspirante)
);

CREATE TABLE IF NOT EXISTS public.tipo_identificacion
(
    id_tipo_identificacion INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nombre character varying(64) NOT NULL,
    observaciones text COLLATE pg_catalog."default",
    CONSTRAINT tipo_identificacion_pkey PRIMARY KEY (id_tipo_identificacion)
);

CREATE TABLE IF NOT EXISTS public.aspirante_identificacion
(
    id_aspirante INTEGER NOT NULL,
    id_tipo_identificacion INTEGER NOT NULL,
    valor character varying(32) NOT NULL,
    imagen_url character varying(64) COLLATE pg_catalog."default",
    observaciones text COLLATE pg_catalog."default",
    CONSTRAINT aspirante_identificacion_pkey PRIMARY KEY (id_aspirante, id_tipo_identificacion)
);

CREATE TABLE IF NOT EXISTS public.aspirante_opcion
(
    id_aspirante_opcion BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_aspirante BIGINT NOT NULL,
    id_opcion character varying(124) COLLATE pg_catalog."default" NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    CONSTRAINT aspirante_opcion_pkey PRIMARY KEY (id_aspirante_opcion)
);

CREATE TABLE IF NOT EXISTS public.distractor
(
    id_distractor BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    valor text COLLATE pg_catalog."default" NOT NULL,
    activo boolean NOT NULL,
    imagen_url character varying(64) COLLATE pg_catalog."default",
    CONSTRAINT distractor_pkey PRIMARY KEY (id_distractor)
);

CREATE TABLE IF NOT EXISTS public.distractor_area_conocimiento
(
    id_distractor BIGINT NOT NULL,
    id_area_conocimiento INTEGER NOT NULL,
    observaciones text COLLATE pg_catalog."default",
    CONSTRAINT distractor_area_pkey PRIMARY KEY (id_distractor, id_area_conocimiento)
);

CREATE TABLE IF NOT EXISTS public.jornada
(
    id_jornada BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nombre character varying(124) NOT NULL,
    fecha_inicio timestamp with time zone NOT NULL,
    fecha_fin timestamp with time zone NOT NULL,
    observaciones text COLLATE pg_catalog."default",
    CONSTRAINT jornada_pkey PRIMARY KEY (id_jornada)
);

CREATE TABLE IF NOT EXISTS public.jornada_aula
(
    id_jornada BIGINT NOT NULL,
    id_aula character varying(124) COLLATE pg_catalog."default" NOT NULL,
    observaciones text COLLATE pg_catalog."default",
    CONSTRAINT jornada_aula_pkey PRIMARY KEY (id_jornada, id_aula)
);

CREATE TABLE IF NOT EXISTS public.pregunta
(
    id_pregunta BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    valor text COLLATE pg_catalog."default" NOT NULL,
    activo boolean,
    imagen_url character varying(64) COLLATE pg_catalog."default",
    observaciones text COLLATE pg_catalog."default",
    CONSTRAINT pregunta_pkey PRIMARY KEY (id_pregunta)
);

CREATE TABLE IF NOT EXISTS public.pregunta_area_conocimiento
(
    id_pregunta BIGINT NOT NULL,
    id_area_conocimiento INTEGER NOT NULL,
    observaciones text COLLATE pg_catalog."default",
    CONSTRAINT pregunta_area_pkey PRIMARY KEY (id_pregunta, id_area_conocimiento)
);

CREATE TABLE IF NOT EXISTS public.pregunta_distractor
(
    id_pregunta BIGINT NOT NULL,
    id_distractor BIGINT NOT NULL,
    correcto boolean NOT NULL,
    observaciones text COLLATE pg_catalog."default",
    CONSTRAINT pregunta_distractor_pkey PRIMARY KEY (id_pregunta, id_distractor)
);

-- segmento examen
CREATE TABLE IF NOT EXISTS public.prueba
(
    id_prueba BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_tipo_prueba INTEGER NOT NULL,
    nombre character varying(124) COLLATE pg_catalog."default" NOT NULL,
    indicaciones text COLLATE pg_catalog."default" NOT NULL,
    puntaje_maximo numeric(5, 2) NOT NULL,
    nota_aprobacion numeric(5, 2) NOT NULL,
    duracion integer NOT NULL,
    fecha_creacion timestamp with time zone DEFAULT now(),
    CONSTRAINT prueba_pkey PRIMARY KEY (id_prueba)
);

-- segmento - clave
CREATE TABLE IF NOT EXISTS public.prueba_clave
(
    id_prueba_clave BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_prueba BIGINT NOT NULL,
    nombre character varying(64) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT prueba_clave_pkey PRIMARY KEY (id_prueba_clave)
);

-- intermedio segmento - clave &  materia
CREATE TABLE IF NOT EXISTS public.prueba_clave_area_conocimiento
(
    id_prueba_clave BIGINT NOT NULL,
    id_area_conocimiento INTEGER NOT NULL,
    cantidad integer,
    porcentaje numeric(5, 2),
    CONSTRAINT prueba_clave_area_conocimiento_pkey PRIMARY KEY (id_prueba_clave, id_area_conocimiento)
);

-- intermedio segmento - clave - materia & pregunta
CREATE TABLE IF NOT EXISTS public.prueba_clave_area_conocimiento_pregunta
(
    id_prueba_clave BIGINT NOT NULL,
    id_area_conocimiento INTEGER NOT NULL,
    id_pregunta BIGINT NOT NULL,
    porcentaje numeric(5, 2) NOT NULL,
    CONSTRAINT prueba_clave_area_conocimiento_pregunta_pkey PRIMARY KEY (id_prueba_clave, id_area_conocimiento, id_pregunta)
);

-- intermedio segmento - clave - materia - pregunta & distractor
CREATE TABLE IF NOT EXISTS public.prueba_clave_area_conocimiento_pregunta_distractor
(
    id_prueba_clave BIGINT NOT NULL,
    id_area_conocimiento INTEGER NOT NULL,
    id_pregunta BIGINT NOT NULL,
    id_distractor BIGINT NOT NULL,
    fecha_creacion timestamp with time zone DEFAULT now(),
    observaciones text COLLATE pg_catalog."default",
    CONSTRAINT prueba_clave_area_conocimiento_pregunta_distractor_pkey PRIMARY KEY (id_prueba_clave, id_area_conocimiento, id_pregunta, id_distractor)
);

CREATE TABLE IF NOT EXISTS public.prueba_jornada
(
    id_prueba BIGINT NOT NULL,
    id_jornada BIGINT NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    observaciones text COLLATE pg_catalog."default",
    CONSTRAINT prueba_jornada_pkey PRIMARY KEY (id_prueba, id_jornada)
);

CREATE TABLE IF NOT EXISTS public.prueba_jornada_aula_aspirante_opcion
(
    id_prueba BIGINT NOT NULL,
    id_jornada BIGINT NOT NULL,
    id_aula character varying(124) COLLATE pg_catalog."default" NOT NULL,
    id_aspirante_opcion BIGINT NOT NULL,
    activo boolean NOT NULL,
    fecha timestamp with time zone,
    CONSTRAINT prueba_jornada_aula_aspirante_opcion_pkey PRIMARY KEY (id_prueba, id_jornada, id_aula, id_aspirante_opcion)
);

CREATE TABLE IF NOT EXISTS public.prueba_jornada_aula_aspirante_opcion_examen
(
    id_prueba BIGINT NOT NULL,
    id_jornada BIGINT NOT NULL,
    id_aula character varying(124) COLLATE pg_catalog."default" NOT NULL,
    id_aspirante_opcion BIGINT NOT NULL,
    resultado numeric(5, 2) NOT NULL,
    fecha_resultado timestamp with time zone NOT NULL,
    imagen_url character varying(64) COLLATE pg_catalog."default",
    observaciones text,
    CONSTRAINT prueba_jornada_aula_aspirante_opcion_examen_pkey PRIMARY KEY (id_prueba, id_jornada, id_aula, id_aspirante_opcion)
);

CREATE TABLE IF NOT EXISTS public.tipo_prueba
(
    id_tipo_prueba INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    valor text COLLATE pg_catalog."default" NOT NULL,
    activo boolean NOT NULL,
    observaciones text,
    CONSTRAINT tipo_prueba_pkey PRIMARY KEY (id_tipo_prueba)
);


-- Definicion de FK


ALTER TABLE IF EXISTS public.area_conocimiento
    ADD CONSTRAINT fk_area_conocimiento_padre FOREIGN KEY (id_area_conocimiento_padre)
    REFERENCES public.area_conocimiento (id_area_conocimiento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.aspirante_opcion
    ADD CONSTRAINT fk_aspirante_opcion_aspirante FOREIGN KEY (id_aspirante)
    REFERENCES public.aspirante (id_aspirante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.distractor_area_conocimiento
    ADD CONSTRAINT fk_distractor_area_conocimiento_area_conocimiento FOREIGN KEY (id_area_conocimiento)
    REFERENCES public.area_conocimiento (id_area_conocimiento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.distractor_area_conocimiento
    ADD CONSTRAINT fk_distractor_area_conocimiento_distractor FOREIGN KEY (id_distractor)
    REFERENCES public.distractor (id_distractor) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.jornada_aula
    ADD CONSTRAINT fk_jornada_aula_jornada FOREIGN KEY (id_jornada)
    REFERENCES public.jornada (id_jornada) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pregunta_area_conocimiento
    ADD CONSTRAINT fk_pregunta_area_conocimiento_area_conocimiento FOREIGN KEY (id_area_conocimiento)
    REFERENCES public.area_conocimiento (id_area_conocimiento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pregunta_area_conocimiento
    ADD CONSTRAINT fk_pregunta_area_conocimiento_pregunta FOREIGN KEY (id_pregunta)
    REFERENCES public.pregunta (id_pregunta) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pregunta_distractor
    ADD CONSTRAINT fk_pregunta_distractor_distractor FOREIGN KEY (id_distractor)
    REFERENCES public.distractor (id_distractor) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pregunta_distractor
    ADD CONSTRAINT fk_pregunta_distractor_pregunta FOREIGN KEY (id_pregunta)
    REFERENCES public.pregunta (id_pregunta) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prueba
    ADD CONSTRAINT fk_prueba_tipo_prueba FOREIGN KEY (id_tipo_prueba)
    REFERENCES public.tipo_prueba (id_tipo_prueba) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prueba_clave
    ADD CONSTRAINT fk_prueba_clave_prueba FOREIGN KEY (id_prueba)
    REFERENCES public.prueba (id_prueba) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prueba_clave_area_conocimiento
    ADD CONSTRAINT fk_prueba_clave_area_conocimiento_area_conocimiento FOREIGN KEY (id_area_conocimiento)
    REFERENCES public.area_conocimiento (id_area_conocimiento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prueba_clave_area_conocimiento
    ADD CONSTRAINT fk_prueba_clave_area_conocimiento_prueba_clave FOREIGN KEY (id_prueba_clave)
    REFERENCES public.prueba_clave (id_prueba_clave) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prueba_clave_area_conocimiento_pregunta
    ADD CONSTRAINT fk_prueba_clave_area_conocimiento_pregunta_pregunta FOREIGN KEY (id_pregunta)
    REFERENCES public.pregunta (id_pregunta) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prueba_clave_area_conocimiento_pregunta
    ADD CONSTRAINT fk_prueba_clave_area_conocimiento_pregunta_pcac FOREIGN KEY (id_prueba_clave, id_area_conocimiento)
    REFERENCES public.prueba_clave_area_conocimiento (id_prueba_clave, id_area_conocimiento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prueba_clave_area_conocimiento_pregunta_distractor
    ADD CONSTRAINT fk_prueba_clave_area_conocimiento_pregunta_distractor_d FOREIGN KEY (id_distractor)
    REFERENCES public.distractor (id_distractor) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prueba_clave_area_conocimiento_pregunta_distractor
    ADD CONSTRAINT fk_prueba_clave_area_conocimiento_pregunta_distractor_pcacp FOREIGN KEY (id_prueba_clave, id_area_conocimiento, id_pregunta)
    REFERENCES public.prueba_clave_area_conocimiento_pregunta (id_prueba_clave, id_area_conocimiento, id_pregunta) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prueba_jornada
    ADD CONSTRAINT fk_prueba_jornada_jornada FOREIGN KEY (id_jornada)
    REFERENCES public.jornada (id_jornada) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prueba_jornada
    ADD CONSTRAINT fk_prueba_jornada_prueba FOREIGN KEY (id_prueba)
    REFERENCES public.prueba (id_prueba) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prueba_jornada_aula_aspirante_opcion
    ADD CONSTRAINT fk_prueba_jornada_aula_aspirante_opcion_aspirante_opcion FOREIGN KEY (id_aspirante_opcion)
    REFERENCES public.aspirante_opcion (id_aspirante_opcion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prueba_jornada_aula_aspirante_opcion
    ADD CONSTRAINT fk_prueba_jornada_aula_aspirante_opcion_prueba FOREIGN KEY (id_prueba)
    REFERENCES public.prueba (id_prueba) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prueba_jornada_aula_aspirante_opcion
    ADD CONSTRAINT fk_prueba_jornada_aula_aspirante_opcion_jornada_aula FOREIGN KEY (id_jornada, id_aula)
    REFERENCES public.jornada_aula (id_jornada, id_aula) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prueba_jornada_aula_aspirante_opcion_examen
    ADD CONSTRAINT fk_prueba_jornada_aula_aspirante_opcion_examen_pjaao FOREIGN KEY (id_prueba, id_jornada, id_aula, id_aspirante_opcion)
    REFERENCES public.prueba_jornada_aula_aspirante_opcion (id_prueba, id_jornada, id_aula, id_aspirante_opcion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public.aspirante_identificacion
    ADD CONSTRAINT fk_aspirante_identificacion_aspirante FOREIGN KEY (id_aspirante)
    REFERENCES public.aspirante (id_aspirante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public.aspirante_identificacion
    ADD CONSTRAINT fk_aspirante_identificacion_tipo_identificacion FOREIGN KEY (id_tipo_identificacion)
    REFERENCES public.tipo_identificacion (id_tipo_identificacion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


-- Definicion de UQ


ALTER TABLE IF EXISTS public.area_conocimiento
ADD CONSTRAINT uq_area_conocimiento_padre_nombre
UNIQUE (id_area_conocimiento_padre, nombre);

END;
